/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by <kernel>/tools/hardware/outputs/c_header.py.
 */

#pragma once

#define PHYS_BASE_RAW 0xc0000000

#ifndef __ASSEMBLER__

#include <config.h>
#include <mode/hardware.h>  /* for KDEV_BASE */
#include <linker.h>         /* for BOOT_RODATA */
#include <basic_types.h>    /* for p_region_t, kernel_frame_t (arch/types.h) */

/* Wrap raw physBase location constant to give it a symbolic name in C that's
 * visible to verification. This is necessary as there are no real constants
 * in C except enums, and enums constants must fit in an int.
 */
static inline CONST word_t physBase(void)
{
    return PHYS_BASE_RAW;
}

/* INTERRUPTS */
/* INTERRUPT_VGIC_MAINTENANCE generated from /interrupt-controller@30800000 */
#define INTERRUPT_VGIC_MAINTENANCE 25
/* INTERRUPT_VTIMER_EVENT generated from /timer */
#define INTERRUPT_VTIMER_EVENT 27
/* KERNEL_TIMER_IRQ generated from /timer */
#ifdef CONFIG_ARM_HYPERVISOR_SUPPORT
#define KERNEL_TIMER_IRQ 26
#else
#define KERNEL_TIMER_IRQ 27
#endif /* CONFIG_ARM_HYPERVISOR_SUPPORT */
/* KERNEL DEVICES */
#define UART_PPTR (KDEV_BASE + 0x0)
#define GICD_PPTR (KDEV_BASE + 0x1000)
#define GICR_PPTR (KDEV_BASE + 0x11000)

static const kernel_frame_t BOOT_RODATA kernel_device_frames[] = {
    #ifdef CONFIG_PRINTING
    /* /soc/uart@2800d000 */
    {
        .paddr = 0x2800d000,
        .pptr = UART_PPTR,
        .armExecuteNever = true,
        .userAvailable = true
    },
    #endif /* CONFIG_PRINTING */
    /* /interrupt-controller@30800000 */
    {
        .paddr = 0x30800000,
        .pptr = GICD_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30801000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x2000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30802000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x3000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30803000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x4000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30804000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x5000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30805000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x6000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30806000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x7000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30807000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x8000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30808000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x9000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30809000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xa000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080a000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xb000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080b000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xc000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080c000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xd000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080d000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xe000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080e000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xf000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080f000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x10000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    /* /interrupt-controller@30800000 */
    {
        .paddr = 0x30880000,
        .pptr = GICR_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30881000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x12000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30882000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x13000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30883000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x14000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30884000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x15000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30885000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x16000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30886000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x17000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30887000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x18000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30888000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x19000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30889000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088a000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088b000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088c000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088d000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088e000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088f000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x20000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30890000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x21000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30891000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x22000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30892000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x23000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30893000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x24000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30894000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x25000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30895000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x26000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30896000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x27000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30897000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x28000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30898000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x29000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30899000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089a000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089b000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089c000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089d000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089e000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089f000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x30000,
        .armExecuteNever = true,
        .userAvailable = false
    },
};

/* Elements in kernel_device_frames may be enabled in specific configurations
 * only, but the ARRAY_SIZE() macro will automatically take care of this.
 * However, one corner case remains unsolved where all elements are disabled
 * and this becomes an empty array effectively. Then the C parser used in the
 * formal verification process will fail, because it follows the strict C rules
 * which do not allow empty arrays. Luckily, we have not met this case yet...
 */
#define NUM_KERNEL_DEVICE_FRAMES ARRAY_SIZE(kernel_device_frames)

/* PHYSICAL MEMORY */
static const p_region_t BOOT_RODATA avail_p_regs[] = {
    /* /memory@b0000000 */
    {
        .start = 0xc0000000,
        .end   = 0xde000000
    },
    /* /memory@b0000000 */
    {
        .start = 0xde420000,
        .end   = 0xf0000000
    },
};

#endif /* !__ASSEMBLER__ */
