/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by <kernel>/tools/hardware/outputs/c_header.py.
 */

#pragma once

#define PHYS_BASE_RAW 0xb0000000

#ifndef __ASSEMBLER__

#include <config.h>
#include <mode/hardware.h>  /* for KDEV_BASE */
#include <linker.h>         /* for BOOT_RODATA */
#include <basic_types.h>    /* for p_region_t, kernel_frame_t (arch/types.h) */

/* Wrap raw physBase location constant to give it a symbolic name in C that's
 * visible to verification. This is necessary as there are no real constants
 * in C except enums, and enums constants must fit in an int.
 */
static inline CONST word_t physBase(void)
{
    return PHYS_BASE_RAW;
}

/* INTERRUPTS */
/* INTERRUPT_VGIC_MAINTENANCE generated from /interrupt-controller@30800000 */
#define INTERRUPT_VGIC_MAINTENANCE 25
/* INTERRUPT_VTIMER_EVENT generated from /timer */
#define INTERRUPT_VTIMER_EVENT 27
/* KERNEL_TIMER_IRQ generated from /timer */
#ifdef CONFIG_ARM_HYPERVISOR_SUPPORT
#define KERNEL_TIMER_IRQ 26
#else
#define KERNEL_TIMER_IRQ 27
#endif /* CONFIG_ARM_HYPERVISOR_SUPPORT */
/* KERNEL DEVICES */
#define UART_PPTR (KDEV_BASE + 0x0)
#define GICD_PPTR (KDEV_BASE + 0x1000)
#define GICR_PPTR (KDEV_BASE + 0x11000)

static const kernel_frame_t BOOT_RODATA kernel_device_frames[] = {
    #ifdef CONFIG_PRINTING
    /* /soc/uart@2800d000 */
    {
        .paddr = 0x2800d000,
        .pptr = UART_PPTR,
        .armExecuteNever = true,
        .userAvailable = true
    },
    #endif /* CONFIG_PRINTING */
    /* /interrupt-controller@30800000 */
    {
        .paddr = 0x30800000,
        .pptr = GICD_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30801000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x2000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30802000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x3000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30803000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x4000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30804000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x5000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30805000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x6000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30806000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x7000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30807000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x8000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30808000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x9000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30809000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xa000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080a000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xb000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080b000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xc000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080c000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xd000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080d000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xe000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080e000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0xf000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3080f000,
        /* contains GICD_PPTR */
        .pptr = KDEV_BASE + 0x10000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    /* /interrupt-controller@30800000 */
    {
        .paddr = 0x30880000,
        .pptr = GICR_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30881000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x12000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30882000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x13000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30883000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x14000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30884000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x15000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30885000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x16000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30886000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x17000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30887000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x18000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30888000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x19000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30889000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088a000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088b000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088c000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088d000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088e000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x1f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3088f000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x20000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30890000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x21000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30891000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x22000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30892000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x23000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30893000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x24000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30894000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x25000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30895000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x26000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30896000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x27000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30897000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x28000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30898000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x29000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x30899000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089a000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089b000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089c000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089d000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089e000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x2f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x3089f000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x30000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x31000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x32000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x33000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x34000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x35000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x36000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x37000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x38000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x39000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308a9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308aa000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ab000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ac000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ad000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ae000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x3f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308af000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x40000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x41000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x42000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x43000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x44000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x45000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x46000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x47000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x48000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x49000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308b9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ba000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308bb000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308bc000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308bd000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308be000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x4f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308bf000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x50000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x51000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x52000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x53000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x54000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x55000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x56000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x57000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x58000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x59000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308c9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ca000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308cb000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308cc000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308cd000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ce000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x5f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308cf000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x60000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x61000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x62000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x63000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x64000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x65000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x66000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x67000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x68000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x69000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308d9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308da000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308db000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308dc000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308dd000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308de000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x6f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308df000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x70000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x71000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x72000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x73000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x74000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x75000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x76000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x77000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x78000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x79000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308e9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ea000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308eb000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ec000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ed000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ee000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x7f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ef000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x80000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f0000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x81000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f1000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x82000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f2000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x83000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f3000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x84000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f4000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x85000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f5000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x86000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f6000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x87000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f7000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x88000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f8000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x89000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308f9000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8a000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308fa000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8b000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308fb000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8c000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308fc000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8d000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308fd000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8e000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308fe000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x8f000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    {
        .paddr = 0x308ff000,
        /* contains GICR_PPTR */
        .pptr = KDEV_BASE + 0x90000,
        .armExecuteNever = true,
        .userAvailable = false
    },
};

/* Elements in kernel_device_frames may be enabled in specific configurations
 * only, but the ARRAY_SIZE() macro will automatically take care of this.
 * However, one corner case remains unsolved where all elements are disabled
 * and this becomes an empty array effectively. Then the C parser used in the
 * formal verification process will fail, because it follows the strict C rules
 * which do not allow empty arrays. Luckily, we have not met this case yet...
 */
#define NUM_KERNEL_DEVICE_FRAMES ARRAY_SIZE(kernel_device_frames)

/* PHYSICAL MEMORY */
static const p_region_t BOOT_RODATA avail_p_regs[] = {
    /* /memory@b0000000 */
    {
        .start = 0xb0000000,
        .end   = 0xe0000000
    },
};

#endif /* !__ASSEMBLER__ */
